### ISSUE TITLE
Source of recovered / deaths / tested

### ISSUE THREAD

**Issue by scign** [ccodwg/Covid19Canada#1]
First of all curating this data is nothing less than phenomenal, and the dashboard you have created is awesome. Thank you for this public service. I'm curious though about your source for the number recovered, deaths and number tested, as this information doesn't seem to be in the google spreadsheet you linked from the dashboard. Can you point me in the right direction? Thanks!

**Comment by dpjanes** [comment]
https://github.com/Consensas/covid

This dataset has deaths, recoveries, cases and a pile of provincial data about ICO, doctors, etc.

**Comment by ishaberry** [comment]
Thanks so much for your message, we have updated this to include recoveries, deaths, and testing -- and the respective sources. Hope this is helpful!
