### ISSUE TITLE
About health regions

### ISSUE THREAD

**Issue by lou00011** [ccodwg/Covid19Canada#10]
Question about health regions. There is a statscan classification on health regions, but I found that many of the names do not match with the values provided in the data.

https://www150.statcan.gc.ca/n1/pub/82-402-x/2017001/app-ann/ap-an1-eng.htm

Curious if you are using a different definition definition for health regions and if these information are available.

thanks!

**Comment by ishaberry** [comment]
We are using these names and these values, however some of these health regions are outdated-- in which case, we use the centroid of the current health regions.
