### ISSUE TITLE
RE April 15 changes .. not clear if old dataset remains in current Github repo and will no longer be updated? Or will it be deleted entirely?

### ISSUE THREAD

**Issue by sitrucp** [ccodwg/Covid19Canada#102]
Curious to know if I can keep pointing to the old dataset Github repo even if it will no longer be updated? Or will it be deleted entirely and any references no longer valid? Thanks!

**Comment by jeanpaulrsoucy** [comment]
Postponed to April 30 now but yes, the old data will continue to be available at the same URLs.
