### ISSUE TITLE
Could hospitalization data be added?

### ISSUE THREAD

**Issue by snoble** [ccodwg/Covid19Canada#11]
At least one province (BC) has started publishing hospitalization numbers. This seems like an important statistic to follow. Could the available data be added to the spreadsheet?

For BC the daily reports are listed on http://www.bccdc.ca/health-info/diseases-conditions/covid-19/case-counts-press-statements. An example report is http://www.bccdc.ca/Health-Info-Site/Documents/BC_Surveillance_Summary_March_27_final.pdf. I've extracted some of the data here https://docs.google.com/spreadsheets/d/1uz-hq7ncFff92iSh63_G-oFew2O1F_2eHOfr1_zdREg/edit?usp=sharing

**Comment by zahra-travail** [comment]
For Quebec, hospitalization numbers have been given at the daily press conference for a few days. There’s a transcript, so it should be easy to find. 

Start here to check each day’s transcript:
http://www.assnat.qc.ca/fr/calendrier-detaille.html

**Comment by ishaberry** [comment]
Hi there-- Thanks for your message. We recognize that collecting hospitalization information is important however at this time we are not able to collect this as this is not readily available at the individual level across the whole country.
