### ISSUE TITLE
Could you please publish the spatial data?

### ISSUE THREAD

**Issue by own-arc** [ccodwg/Covid19Canada#12]
Hi,

Could you please publish a table showing the coordinates you used for each health region?

Thanks!
-OWN

**Comment by p-smirnov** [comment]
Hi OWN,

Not a maintainer for this repo, but from my conversations with Isha I learned the following:

The regions are taken directly from Public Health Ontario reporting. They should be Public Health Units, the definition of which can be downloaded from Statistics Canada, here: https://www150.statcan.gc.ca/n1/pub/82-402-x/2015001/data-donnees/boundary-limites/mapinfo/HRP035b11m_e.zip

Note that one of the regions defined (#17 if I remember correctly) had a self-intersection by mistake and may need to be edited for some data analysis operations. 

Best,
Petr Smirnov

**Comment by jeanpaulrsoucy** [comment]
@p-smirnov is correct. We used the boundary files for health regions published by Statistics Canada:

https://www150.statcan.gc.ca/n1/pub/82-402-x/2018001/hrbf-flrs-eng.htm

We simply took the centroid of each health region (and had to move a few that ended up in water).

**Comment by own-arc** [comment]
@jeanpaulrsoucy Thanks for the reply - do you have the coordinates of these locations (the centroids) in tabular format somewhere?

**Comment by own-arc** [comment]
> Hi OWN,
> 
> Not a maintainer for this repo, but from my conversations with Isha I learned the following:
> 
> The regions are taken directly from Public Health Ontario reporting. They should be Public Health Units, the definition of which can be downloaded from Statistics Canada, here: https://www150.statcan.gc.ca/n1/pub/82-402-x/2015001/data-donnees/boundary-limites/mapinfo/HRP035b11m_e.zip
> 
> Note that one of the regions defined (#17 if I remember correctly) had a self-intersection by mistake and may need to be edited for some data analysis operations.
> 
> Best,
> Petr Smirnov

Thanks!

**Comment by own-arc** [comment]
> @p-smirnov is correct. We used the boundary files for health regions published by Statistics Canada:
> 
> https://www150.statcan.gc.ca/n1/pub/82-402-x/2018001/hrbf-flrs-eng.htm
> 
> We simply took the centroid of each health region (and had to move a few that ended up in water).

Thanks for the reply! Would you happen to have the coordinates of these centroids in tabular format somewhere?
