### ISSUE TITLE
Order by "Cases per 100,000 population" does not work on dashboard

### ISSUE THREAD

**Issue by sgould420** [ccodwg/Covid19Canada#13]
Just so you are aware..  on the dashboard at https://art-bd.shinyapps.io/covid19canada/ 
if you try to order the table  at the bottom of the overview page by "Cases per 100,000 population", the order is wrong for both ascending and descending order.

**Comment by jeanpaulrsoucy** [comment]
Thank you for the bug report. Should be fixed now.
