### ISSUE TITLE
Error on map labelling

### ISSUE THREAD

**Issue by dwsin** [ccodwg/Covid19Canada#14]
an error on the label for Oakville area see map below under cumulative confirmed cases.
![image](https://user-images.githubusercontent.com/7118030/77829317-aa9efa80-70f7-11ea-8405-31cbde786414.png)

Also the Email flattenofficial@gmail.com is not recognized by gmail.

Daniel

**Comment by ishaberry** [comment]
Hi There-- we are not running the flatten website. It looks like they are using our data to power their dashboard, but we are not directly involved with their efforts. I would recommend you follow-up with them. Our dashboard can be found here: https://art-bd.shinyapps.io/covid19canada/
