### ISSUE TITLE
Contributing to Spreadsheet

### ISSUE THREAD

**Issue by EricPickup** [ccodwg/Covid19Canada#15]
This is an awesome project. Thanks for doing this.

I've noticed that the data is outdated for my area of Windsor-Essex. I'd love to help contribute to the spreadsheet. I'm a student from the University of Windsor. Would it be possible to get access and contribute to your data set?

**Comment by ishaberry** [comment]
Hi There-- we update the public facing dataset/dashboard once per a day using the ministry of health reports-- we are currently on working on looking at local public health unit reports to backfill cases with missing health regions. 

Thanks so much for your interest. At this moment we are at full capacity on the data curation side, so unfortunately are unable to work on onboarding new members. But as things evolve we will definitely reach out. Thanks again for reaching out!
