### ISSUE TITLE
I can't see where you're getting the numbers for Recovery, for 5 jurisdictions.

### ISSUE THREAD

**Issue by johanley** [ccodwg/Covid19Canada#16]
Hi, 

I can't see where you're getting the numbers for _Recovered_, for 5 jurisdictions.

I'm using these links as base:

NS
https://novascotia.ca/coronavirus/ 

QC
https://www.msss.gouv.qc.ca/professionnels/maladies-infectieuses/coronavirus-2019-ncov/ 

AB
https://www.alberta.ca/covid-19-alberta-data.aspx  

NB
https://www2.gnb.ca/content/gnb/en/departments/ocmoh/cdc/content/respiratory_diseases/coronavirus.html 

NL
https://www.gov.nl.ca/covid-19/

Please advise.

- John

**Comment by ishaberry** [comment]
Hi there-- all of these links are the base to where we find the numbers of recoveries. Usually they are posted on the website or they are in the daily press releases or press conferences (so may have to do some exploration on the website).

For the provinces you have linked to:
NS: https://novascotia.ca/news/release/?id=20200329001
QC: http://www.assnat.qc.ca/fr/actualites-salle-presse/conferences-points-presse/index.html
NB: https://www2.gnb.ca/content/gnb/en/news/news_release.2020.03.0164.html
NL: media briefing (https://www.gov.nl.ca/covid-19/)
AB: Chief medical officer updates (https://www.alberta.ca/coronavirus-info-for-albertans.aspx)

**Comment by johanley** [comment]
Man oh man, they sure aren't making it easy for you...
Thanks for the info.
