### ISSUE TITLE
Some more ideas for graphing the data

### ISSUE THREAD

**Issue by bhauman** [ccodwg/Covid19Canada#17]
I created the following from the John Hopkins data:

https://rigsomelight.com/canada_covid

It contains some graphing ideas that I got from the Financial Times and talking to friends.

Mainly providing a number of days since first case as an X value and looking at percentage of population as a Y value.  You may be interested in putting these on your dashboard.

I'm available if you need someone to work on it.

**Comment by ishaberry** [comment]
Thanks so much for your email and interest. At this moment we are at full capacity on the data curation/visualization side, so unfortunately are unable to work on onboarding new members. But as things evolve we will definitely reach out. Thanks again for reaching out!
