### ISSUE TITLE
Postal Codes

### ISSUE THREAD

**Issue by ratneshchandna** [ccodwg/Covid19Canada#18]
Hi all,

Love the effort so far. I am interested in creating a project that displays this data visually on a map to neighbourhood detail. This won’t be possible without postal codes. 

How challenging would it be to get postal codes? I realised just the first three alphanumerics are good enough to show a neighbourhood close up (also mitigating any privacy concerns). 

Ratnesh

**Comment by ishaberry** [comment]
Hi there-- all of our data is curated from publicly available sources. At the moment the highest level of spatial resolution that is available publicly is at the health region-level, which is what we are reporting. We are not collecting information at the postal code level.

**Comment by devanshkaloti** [comment]
@ratneshchandna 
Hi Ratnesh, 

I just want to mention that while postal codes aren't available for case data, on https://virihealth.com/full-details/ you can find neighborhood detail for mortality (in the details it mentions the hospital where the person passed away from) 

I am not affiliated in any way with the website, but I thought it might help in whatever you are doing. 

Thanks,
Devansh
