### ISSUE TITLE
Stability of Provincial Case

### ISSUE THREAD

**Issue by dpjanes** [ccodwg/Covid19Canada#2]
Are you assigning this case number, or is this case number assigned by the province? Looking to see if I can just this for joining with an Ontario dataset.

https://github.com/Consensas/covid

**Comment by ishaberry** [comment]
Hi there-- the Province provides case numbers then ours match (e.g. Ontario). However regions that are just providing daily numbers, we assign case IDs sequentially. Hope this is helpful.
