### ISSUE TITLE
Format of numeric columns

### ISSUE THREAD

**Issue by jsumnerPhD** [ccodwg/Covid19Canada#20]
Thanks so much for the repo and maintaining the spreadsheet.  In the spreadsheet, would it be possible to keep columns with numerical values, purely numeric?  The cumulative_testing column on the Testing tab has asterisks on some numbers, which can cause (small) headaches when importing the data.  Could the asterisk be in the column beside instead?

Cheers!
Jon

**Comment by ishaberry** [comment]
Hi Jon-- thanks for your message. We have flagged this issue-- it is based on the way we input the data/pull the data between different sheets. The row numbers change each day so putting a star in the next column would not match with the point it is meant to. We'll work on this and aim to come up with a solution in the near future.

**Comment by jeanpaulrsoucy** [comment]
Hi @jsumnerPhD, should be fixed!

**Comment by jsumnerPhD** [comment]
Excellent!
