### ISSUE TITLE
health_region values do not all correspond to official boundaries

### ISSUE THREAD

**Issue by sitrucp** [ccodwg/Covid19Canada#22]
Where are health_region values coming from? There are some variances from official health region/authorities boundaries.

Sask has 13 health region/authorities eg https://www150.statcan.gc.ca/n1/pub/82-402-x/2017001/maps-cartes/rm-cr10-eng.htm but Google Sheet has only 6 eg Central, Far North, North
Regina, Saskatoon & South

Thanks

**Comment by jeanpaulrsoucy** [comment]
Hi, Saskatchewan amalgamated all of their health authorities into a single health authority in 2017 (https://en.wikipedia.org/wiki/Saskatchewan_Health_Authority). For some reason, this is not reflected in the official health region boundary file from StatCan.

We are using the areas reported by Sask. on their COVID-19 website. See below.

https://www.saskatchewan.ca/government/health-care-administration-and-provider-resources/treatment-procedures-and-guidelines/emerging-public-health-issues/2019-novel-coronavirus/cases-and-risk-of-covid-19-in-saskatchewan

**Comment by sitrucp** [comment]
BTW, I have created a Leaflet map using your 'cases.csv' data to visualize confirmed cases by provincial health region. Not perfect (Sask is still bit messy, HR not reported not showing) but gets most data onto map. https://sitrucp.github.io/canada_covid_health_regions/
