### ISSUE TITLE
Would you be able to provide data for recoveries? 

### ISSUE THREAD

**Issue by joshjpark** [ccodwg/Covid19Canada#23]
Thanks!

**Comment by jeanpaulrsoucy** [comment]
https://github.com/ishaberry/Covid19Canada/blob/master/recovered_cumulative.csv

**Comment by joshjpark** [comment]
Firstly, thank you for maintaining the spreadsheet and this repo. 

I was looking at recoveries data in _Covid19Canada/timeseries_hr/_ in particular. Would that be available as well?

I am creating a web-app providing info for each province & regions and I am missing # of recoveries for each region ATM. Thanks again!

**Comment by bzagor1** [comment]
Thank you all contributors for creating this repo, its nice to get the data
across Canada for each health region!

I was hoping to dig a little further into the data, is there any more
information you can provide as the the missing-ness of the data, in
particular, age, sex.  For example, how do you collect this information
and  how are the missing values updated over time?

I am sure I saying what you already know that its difficult to interpret
these variables when they are missing 96%.

Still, I am incredibly grateful your time and effort on this.

Best Regards, Brandon
