### ISSUE TITLE
Ontario testing

### ISSUE THREAD

**Issue by stephenpetersen** [ccodwg/Covid19Canada#26]
Cumulative test numbers in Ontario for Mar-29 or Mar-30 appear incorrect. The number of tests on Mar-29 is higher, which should not be true.

**Comment by ishaberry** [comment]
Hi there--
Thanks for pointing this out. We'll make a note of this as a potential change in reporting of tests. 
I have just gone back and looked at this on a webarchive:
March 29: https://web.archive.org/web/20200329231512/https://www.ontario.ca/page/2019-novel-coronavirus
March 30: https://web.archive.org/web/20200330202138/https://www.ontario.ca/page/2019-novel-coronavirus

These numbers are indeed what was reported by the Ministry, which suggests there may have been a change in reporting of tests.
