### ISSUE TITLE
Cases.csv not being updated - is Google Sheet now official data source?

### ISSUE THREAD

**Issue by sitrucp** [ccodwg/Covid19Canada#27]
Cases.csv not being updated daily as was before. I notice today that Google Sheet has been updated but cases.csv has not.

Should we now consider Google Sheet as official regularly updated data source?

Thanks for all your good work!

**Comment by donaldzou** [comment]
@sitrucp Same problem, thinking of moving to fetch google sheet instead of the csv file from github

**Comment by jeanpaulrsoucy** [comment]
Hi, we had a hiccup that resulted in the data from 2020-04-19 not being updated on GitHub until the morning of 2020-04-20. You may continue pulling from GitHub - we do not foresee this happening again.
