### ISSUE TITLE
Difference between this dataset and others

### ISSUE THREAD

**Issue by obilodeau** [ccodwg/Covid19Canada#3]
First, thanks for the great service!

I was wondering if you had an explanation on the variation on some of the data. For example, today's total number of cases on the dashboard (727) varies from [Canada.ca's Public Health Services](https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html) (621)

I pull data from https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/ and also see a similar discrepancy.

**Comment by ishaberry** [comment]
Thanks for your message. We are using both confirmed positive and presumptive positives, these are reported by each of the ministries of health and news media sources. There is likely a lag between some sources (such as PHAC) and our cases. 

We are also only reported by date of report, this does not include date of symptom onset (which is undeniably a better indicator) but is not as frequently publicly reported. Hope this helps.
