### ISSUE TITLE
Reported cases/deaths are not using proper health regions

### ISSUE THREAD

**Issue by pisarenko-net** [ccodwg/Covid19Canada#32]
Looking at the health region data it looks like the names of the regions are incomplete. The full list of health regions are listed at https://www150.statcan.gc.ca/n1/pub/82-402-x/2015002/app-ann/ap-an1-eng.htm

Among the values in the data I see "Fraser" but this is ambiguous and can't be mapped to the actual health regions which are:

- 5921 Fraser East Health Service Delivery Area
- 5922 Fraser North Health Service Delivery Area
- 5923 Fraser South Health Service Delivery Area

Hoping this data is available somewhere upstream...

**Comment by jeanpaulrsoucy** [comment]
Hi, BCCDC reports at the Health Authority level.

http://www.bccdc.ca/health-info/diseases-conditions/covid-19/data

Health Service Delivery Areas aggregate to Health Authorities.

https://www12.statcan.gc.ca/health-sante/82-228/help-aide/Q01.cfm?Lang=E

We use the term "health region" as it is the closest thing to a common term we have between provinces.
