### ISSUE TITLE
data entry error recovered_cumulative.csv

### ISSUE THREAD

**Issue by Kuan-Liu** [ccodwg/Covid19Canada#33]
Dear team,

The cumulative recovered counts for SK for May 31, 2020 (most recent update) should be 582 instead of 682.

see line number 992 on data page, https://github.com/ishaberry/Covid19Canada/blob/master/recovered_cumulative.csv#L992

31-05-2020 | Saskatchewan | 682 <- should be 582

https://www.saskatchewan.ca/government/health-care-administration-and-provider-resources/treatment-procedures-and-guidelines/emerging-public-health-issues/2019-novel-coronavirus/cases-and-risk-of-covid-19-in-saskatchewan

Many thanks,
Kuan

**Comment by jeanpaulrsoucy** [comment]
Got it, thanks!
