### ISSUE TITLE
Detailed Ontario data available in CSV format

### ISSUE THREAD

**Issue by walterdnes** [ccodwg/Covid19Canada#41]
Hello;

  Detailed Province of Ontario data is available in CSV format at

https://data.ontario.ca/dataset/f4f86e54-872d-43f8-8a86-3892fd3cb5e6/resource/ed270bb8-340b-41f9-a7c6-e8ef587e6d11/download/covidtesting.csv

It is updated daily at approximately 10:15 AM Eastern. Lots of interesting stuff. Some examples are...

* Column E is currently acive cases, noticeably lower than your count

* Column G is cumulative deaths. Subtract previous day from current day to get deaths occuring on the most recent day..

* Column H is cumulative number of positive tests. Subtract previous day from current day to get positives occuring on the most recent day.. I believe Ontario currently uses number of tests, not number of people, in the count.

* Column J number of tests run in past 24 hours.

And I'm sure there is other stuff you'll be interested in. The province also has detailed daily PDF reports at https://covid-19.ontario.ca/covid-19-epidemiologic-summaries-public-health-ontario#daily

The PDF files have breakdowns by Public Health Unit going back to June 11 (June 9th and 10th data). I've been scraping the daily PDFs for daily case counts for each health unit. I can upload the daily PHU new cases data if you're interested. Note that with "adjustments", you'll see occasional days with negative case counts.

**Comment by ishaberry** [comment]
Hi there -- we are aware of this dataset, it is great! We are currently working to link our dataset to this one to obtain more demographic information. 

Our dataset is pulled directly from Public Health Units, as the numbers are more up to date. We provide a further explanation of this here: https://opencovid.ca/work/data-faq/

**Comment by jeanpaulrsoucy** [comment]
Hey @walterdnes. Thanks for the link---I was actually not aware of this dataset. Our active case numbers for Ontario are higher than the province's because we use case numbers from PHUs (which are ahead of the confirmed cases dataset from the province) but recovered numbers from the province.

By the way, if you have old versions of this dataset ("covidtesting.csv"), I'd love to have them for our sister project, which is an archive of timestamped versions of official Canadian COVID-19 data: https://github.com/jeanpaulrsoucy/covid-19-canada-gov-data

Scraped versions of the daily epidemiological summaries would be of interest for this project, too!

**Comment by walterdnes** [comment]
In-Reply-To: <ishaberry/Covid19Canada/issues/41/681177079@github.com>

On Wed, Aug 26, 2020 at 04:34:33PM -0700, Jean-Paul R. Soucy wrote

> By the way, if you have old versions of this dataset ("covidtesting.csv"),
> I'd love to have them for our sister project, which is an archive
> of timestamped versions of official Canadian COVID-19 data:
> https://github.com/jeanpaulrsoucy/covid-19-canada-gov-data

  Sorry, I only keep the latest version.  The name doesn't change, and
the only difference seems to be an extra line added to the file every day.

> Scraped versions of the daily epidemiological summaries would be of
> interest for this project, too!

  I'm retired, and have time on my hands.  I follow the COVID-19 thread
on the dslreports.com CanChat forum and post a daily update based on
Ontario numbers.  See my August 26th post at...

https://www.dslreports.com/forum/r32856585-

  Click and download the attachment "phusum.zip" in that post.  It has
positive test counts data going back to June 11 when Ontario started
including this in the PDF.  These are the numbers the media announces
just after 10:30 AM daily.  The zipped "phusum.csv" file has 4 columns.

* date of report
* PHU name
* count of new positive tests 2 days ago
* count of new positive tests 1 day  ago

  The first line in "phusum.csv" is...

2020-06-11,"Northwestern Health Unit",2,0

...which means

* report supposed to be posted 10:30 AM on 2020-06-11
* data is for "Northwestern Health Unit" PHU (public health unit)
* 2 new positive tests 2020-06-09
* 0 new positive tests 2020-06-10

  I'm not a "real programmer".  My strength is advanced bash scripting.
To get the Ontario data breakdowns by PHU, I run a script that feeds the
daily epidemiological summaries through "pdf2text", and parses the text
output and reformats as a CSV file that I upload to the dslreports
forum.  I only process one PDF file at a time.  The format of the PDF
files changes slightly from time-to-time, and I have to tweak the
processing script to match it.

  I've come up with a script to re-format the CSV file to make it
suitable for plotting individual PHUs by date that you may be interested
in.  I'm attaching a zipped version of "phuplot.csv".  It's 36 columns
across...

* DATE
* 34 public health unit new positive counts
* TOTAL ONTARIO new positive counts

  The Ontario data has adjustments resulting in occasional negative new
positives.  August 20th has several N/A* entries due to data upload
problems with IPHIS.

-- 
Walter Dnes <waltdnes@waltdnes.org>
