### ISSUE TITLE
Unusually large decrease in number of active cases in Quebec on 2020-07-16 requires confirmation

### ISSUE THREAD

**Issue by kaionwong** [ccodwg/Covid19Canada#42]
In the active_timeseries_prov.csv, the active cases in Quebec drops from 25,102 to 1,556 in one day (from 2020-07-16 to 2020-07-17). This amount of reduction seems unlikely. Could your team please validate and comment on these unusual figures?

**Comment by jeanpaulrsoucy** [comment]
Thank you for your question.

It's real but results from a definition change in the province. Details here: https://twitter.com/JPSoucy/status/1284180716520185857

Our plan is to retroactively change the entire recovered time series for Quebec, but at the time of the definition change, estimating recovered based on active cases reported by INSPQ produced inconsistent values (covered in the thread above). We will revisit this in the future to see if the time series has been further revised to be consistent with the new definition of recovered.

I'll add this to our dataset FAQ: https://opencovid.ca/work/data-faq/
