### ISSUE TITLE
missing 2 cases in PEI

### ISSUE THREAD

**Issue by osbornejo** [ccodwg/Covid19Canada#43]
Hi,

I believe you are missing two cases from PEI that were added on Sunday Oct 4th, 2020.  See: https://www.cbc.ca/news/canada/prince-edward-island/pei-covid-19-two-cases-1.5750109

The case total is now 61.

The PEI Case Data still has 59 listed, however, the Public Health Agency of Canada Site is reporting the 2 additional cases.

Thanks

**Comment by jeanpaulrsoucy** [comment]
Fixed in tonight's data push. Thanks!
