### ISSUE TITLE
Redesign meta-data / README.md

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19Canada#52]
The meta-data (primarily stored within README.md) is in need of an overhaul. Tasks will be added below as they arise:

- [x] Add instructions for downloading from GitHub for non-technical users
- [ ] Explain differences between various datasets (e.g., recovered_cumulative and recovered_timeseries_prov.csv)

**Comment by calpa** [comment]
I think there should be a 1-minute tutorial of how to use this project, maybe I can write for it.
