### ISSUE TITLE
Maybe chart display is better

### ISSUE THREAD

**Issue by lonlii4ap** [ccodwg/Covid19Canada#58]
This is a very meaningful thing, if you can use the chart display to be more intuitive. I am a web developer and I am willing to build a website for free. If necessary, I can directly reply to github or email to lonlii4ap@gmail.com.

**Comment by jeanpaulrsoucy** [comment]
Hi @lonlii4ap, I'm not sure exactly what you're referring to. Could you explain what you had in mind?

We do have a dashboard powered by our dataset that is available here:

https://art-bd.shinyapps.io/covid19canada/

**Comment by lonlii4ap** [comment]
hi Jean-Paul,the dashboard website is what I mean.You are absolutely right.
