### ISSUE TITLE
Quebec cumulative distribution data

### ISSUE THREAD

**Issue by rdastous** [ccodwg/Covid19Canada#59]
Simple correction

Data show a Quebec cumulative distribution value of 4875 up to the 27th of december. It looks like they were delivered 49,725 by dec 21st, for a total cumulative of 54,600 from that date.

https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/20-279-07WF_Previsions_vaccination.pdf?1609972425

**Comment by ishaberry** [comment]
Hi there thanks for your message-- we retrieve our distribution data from PHAC (https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection/prevention-risks/covid-19-vaccine-treatment/vaccine-rollout.html) which provides the most updated number

**Comment by rdastous** [comment]
Thanks Isha,

It still does not explain how they could administer 3 times more vaccine than the quantity they were delivered.

Probably a ramp-up data discrepancy, hope it will be better in the future

Régis

**Comment by jeanpaulrsoucy** [comment]
Hi --- we've verified the document and updated the number on December 21. This should remove the issue of > 100% of doses administered. The other numbers don't quite line up after that but this is probably just a discrepancy between federal and provincial reporting.

**Comment by mschoettle** [comment]
Hi, I was actually wondering about that too. On the PHAC website there was no such table as of Dec 23rd (based on Wayback Machine, it shows up on Jan 2nd for Dec 31st). Where did you find the distribution before Dec 31st?

**Comment by jeanpaulrsoucy** [comment]
Sporadic news releases, press conferences, etc. There's still some cleanup that can be done of the history, but as I said, it's been difficult to find the exact days prior to the PHAC table.
