### ISSUE TITLE
vaccination (distributed & adminstered) counts for 2 doses

### ISSUE THREAD

**Issue by sitrucp** [ccodwg/Covid19Canada#60]
Thinking about use case of determining % of population that has been fully vaccinated (for Pfizer/BioNTech & Moderna vaccines requiring 2 doses).

Any indication yet if provinces will create a new data point for people that have received 2nd dose, as opposed to recording 2nd dose adminstered as just another single dose administered?

**Comment by ishaberry** [comment]
Hi There-- this is not consistently being reported by all provinces so we are looking for ways to best capture this information and display it in a systematic format. We are a volunteer-run group, so have to prioritize overall data collection processes before we can add new and updated numbers. Thank you for your message!
