### ISSUE TITLE
Additional historical data, including testing numbers

### ISSUE THREAD

**Issue by larsvilhuber** [ccodwg/Covid19Canada#7]
I have been collecting QC ON and NS data on cases and testing. Please feel free to integrate:

https://docs.google.com/spreadsheets/d/1oB6lRKAlNg0LVNXXAXV9d07ka04JWQgBvcqVjHKc21M/edit?usp=sharing

**Comment by ishaberry** [comment]
Thanks so much we will look into this, really appreciate it!
