### ISSUE TITLE
Why are all the ages in the "montreal" health_region "Not Reported"?

### ISSUE THREAD

**Issue by yfarjoun** [ccodwg/Covid19Canada#71]
There seem to be very little age data in the table:

```r
> data=rbind(
  read.table(url("https://github.com/ccodwg/Covid19Canada/raw/master/individual_level/cases_2020.csv"),sep=",",header = T),
  read.table(url("https://github.com/ccodwg/Covid19Canada/raw/master/individual_level/cases_2021.csv"),sep=",",header = T))

> subset(data,province=="Quebec")$age%>%table
.
       40-49        70-79 Not Reported 
           1            1       293858 

```
also in other Provinces, where there's more age data, the vast majority is "Not Reported":

```r
> subset(data,province=="Ontario")$age%>%table
.
          <1          <10          <18          <19          <20          >60          >80          >90 
           1           39            6           37           32            1          138            1 
        0-17         0-19          0-9        10-19      100-109        18-24        18-34        20-29 
         736            8            6           59            1            1         2018          343 
       20-39        30-39        35-44        40-49        40-59        45-64        45-65        50-59 
          60          287          906          278           44         1630            8          346 
       60-69        60-79        65-69        65-74        65-79        70-79        80-89          80+ 
         285           25            1            3          559          161           83          165 
       90-99          90+ Not Reported 
          51            1       307905 
```

How are age-level reports such as in https://www.inspq.qc.ca/covid-19/donnees/age-sexe generated?

**Comment by jeanpaulrsoucy** [comment]
In Quebec specifically, the age data given are cumulative, meaning there is no simple way to assign a particular case (e.g., case in a male aged 60-69 in Montreal) to a particular date.

**Comment by yfarjoun** [comment]
I am sure that you would love, as much as I, to have the full individual level data....but I guess my confusion arose from the fact that it seems that there's more age-data in inspq site (in their plots....but I've been unable to get hold of the raw data....)

Thanks!

**Comment by jeanpaulrsoucy** [comment]
Getting the data from the INSPQ plots is no trouble: they're just CSVs.

You can get some approximation of a time series from my daily snapshots of the files:

**Comment by jeanpaulrsoucy** [comment]
@yfarjoun Getting the data from the INSPQ plots is no trouble: they're just CSVs.

You can get some limited approximation of a time series from my daily snapshots of the files: https://github.com/ccodwg/Covid19CanadaArchive#quebec

Montreal also has some of its own data: https://santemontreal.qc.ca/population/coronavirus-covid-19/situation-du-coronavirus-covid-19-a-montreal/

I've captured snapshots of these files too: https://github.com/ccodwg/Covid19CanadaArchive#montreal

**Comment by yfarjoun** [comment]
That's a great pointer! thanks @jeanpaulrsoucy! 🥳
