### ISSUE TITLE
Discrepency in BC active cases numbers compared to official reports

### ISSUE THREAD

**Issue by jeffgca** [ccodwg/Covid19Canada#74]
I recently combined data in eg https://github.com/ccodwg/Covid19Canada/blob/master/timeseries_prov/active_timeseries_prov.csv#L895 with other data reported in BC government official reports eg [this one](https://news.gov.bc.ca/releases/2021HLTH0025-000724) and noticed a consistent difference between what was in the news report and what is in the data provided here. For example, on April 15 2021 the official report states:

> There are 10,052 active cases of COVID-19 in the province, with 16,217 people under public health monitoring as a result of identified exposure to known cases. A further 104,331 people who tested positive have recovered.

For that row in the csv file, active cases are reported as 10,220.

**Comment by jeanpaulrsoucy** [comment]
Yes, BC uses a different definition of active cases than the standard definition, which is:

```
active cases = total cases - recovered - deaths
```

Their dashboard states:

"Active cases exclude those cases who have died, recovered/discontinued isolation or been lost to follow up." The number lost to follow up is not explicitly given but presumably accounts for the difference.

In most provinces, these cases would be automatically considered recovered after some period of time.

We use the standard definition to harmonize data across provinces the best we can.

**Comment by jeffgca** [comment]
That makes sense to me, thanks for the explanation!
