### ISSUE TITLE
Date formatting for Ontario cases

### ISSUE THREAD

**Issue by OliverCrosby** [ccodwg/Covid19Canada#8]
Ontario cases from 12 to 59 have MM-DD-YYYY date formatting. The rest of the ontario cases are DD-MM-YYYY.

If at all possible, it would be good to have YYYY-MM-DD for all.

**Comment by ishaberry** [comment]
All dates are entered as DD-MM-YYYY on the public sheet. Our data is being fed into a global line list that uses this format, so for consistency we have to keep it like this. Sorry for the inconvenience.
