### ISSUE TITLE
active_timeseries_prov.csv - Incredible Ontario Drop 2021-09-07

### ISSUE THREAD

**Issue by isosphere** [ccodwg/Covid19Canada#81]
Here's a zoom-in of the data in question, looks like something strange happened to the data source:

province | date_active | cumulative_cases | cumulative_recovered | cumulative_deaths | active_cases | active_cases_change
-- | -- | -- | -- | -- | -- | --
Ontario | 05-09-2021 | 575615 | 553549 | 9488 | 12578 | -360
Ontario | 06-09-2021 | 575746 | 553549 | 9488 | 12709 | 131
Ontario | 07-09-2021 | 577727 | 562301 | 9502 | **_5924_** | **_-6785_**
Ontario | 08-09-2021 | 578355 | 563097 | 9518 | 5740 | -184
Ontario | 09-09-2021 | 579232 | 563835 | 9529 | 5868 | 128

**Comment by jeanpaulrsoucy** [comment]
Thanks for the prompt on this. I had mentioned this change in the commit notes but not in the README. You can now read that [here](https://github.com/ccodwg/Covid19Canada#recent-dataset-changes). Long story short, we corrected a long-standing issue with the ON data that caused the active case number to be inflated. Daily diffs should have been more or less correct though, as the problem related to a couple thousand cases from the beginning of the pandemic that never got "confirmed" and thus were not included in the Ministry of Health dataset (but was reported by the provinces).
