### ISSUE TITLE
Question about versioned data for number of cases

### ISSUE THREAD

**Issue by manisci** [ccodwg/Covid19Canada#85]
Hi, 

I was wondering if I will be able to extract versioned data, i.e a snapshot of the number of cases in a specific HRR at a specific time, using the data deposited in this repository. For example, modifications to the number of cases are later done as the backlogs from holidays are distributed correctly, or some cases are later distributed to the right date after further investigation. Can I extract the initial noisy data that was actually available at a specific date, without the later and future modifications and corrections? 

Thank you very much :)

**Comment by jeanpaulrsoucy** [comment]
Sure, you can use a simple Bash script to extract every available version of a file from the git history.

https://gist.github.com/jeanpaulrsoucy/bd76a08144f5dde1a89b88782053edd5

For example, after cloning the git repository, you move the above script into the root directory and run the following command:

```
bash git_export_all_file_versions.sh timeseries_hr/cases_timeseries_hr.csv temp/
```

You will end up with timestamped versions of the `cases_timeseries_hr` file in a directory called `temp`.
