### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by JoeMurray** [ccodwg/Covid19Canada#90]
I'd like to give a small donation of $125 in recognition of the long volunteer hours spent on this. Perhaps it could cover any hosting expenses you have, perhaps only coffee and donuts for some of the people putting in great efforts. Where could I send it?

**Comment by jeanpaulrsoucy** [comment]
Hi Joe,

Thank you for your generous offer! :)

Please send us an email: ccodwg@gmail.com
