### ISSUE TITLE
Saskatchewan 

### ISSUE THREAD

**Issue by TheWorth** [ccodwg/Covid19Canada#98]
Has Saskatchewan stopped reporting cases?

**Comment by jeanpaulrsoucy** [comment]
Yes, as of 2022-02-07.

[Sask. COVID-19 dashboard goes dark in transition to 'Living with COVID'](https://saskatoon.ctvnews.ca/sask-covid-19-dashboard-goes-dark-in-transition-to-living-with-covid-1.5770936)

They are now releasing a weekly PDF report on Thursdays, the first of which was released 2022-02-10: [link to report](https://www.saskatchewan.ca/government/health-care-administration-and-provider-resources/treatment-procedures-and-guidelines/emerging-public-health-issues/2019-novel-coronavirus/cases-and-risk-of-covid-19-in-saskatchewan).

However, the data reported in the Thursday reports are only up to the previous Saturday (i.e., data that would be reported on Sunday under the old daily update cycle). These data have already been reported (last day of regular reporting was Sunday, 2022-02-06), so there is so far nothing new to add.

We should have new data to add on this Thursday, but it will be much less detailed than before unfortunately.
